name: Execute Unit tests
on: 
  push:
    branches:
      - feature/**
      
jobs:
  execute_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Checkout
        uses: action/checkout@4
      - name: execute tests
        run: mvn clean compile test
